package config
package config

import (




















































































}	return defaultVal	}		return val	if val, err := strconv.Atoi(valStr); err == nil {	valStr := getEnv(key, "")func getEnvAsInt(key string, defaultVal int) int {}	return defaultVal	}		return value	if value, exists := os.LookupEnv(key); exists {func getEnv(key string, defaultVal string) string {}	}		},			},				"http://localhost:8080",				"http://localhost:3000",			AllowedOrigins: []string{		CORS: CORSConfig{		},			TimestampTolerance: getEnvAsInt("TIMESTAMP_TOLERANCE", 300), // 5 分钟			SignatureSecret: getEnv("SIGNATURE_SECRET", "signature-secret-key"),			APIKey:          getEnv("API_KEY", ""),		API: APIConfig{		},			ExpireHours: getEnvAsInt("JWT_EXPIRE_HOURS", 24),			Secret:      getEnv("JWT_SECRET", "your-secret-key"),		JWT: JWTConfig{		},			Path: getEnv("DB_PATH", "./data/keyserver.db"),			Type: getEnv("DB_TYPE", "sqlite"),		Database: DatabaseConfig{		},			Env:  getEnv("ENV", "development"),			Port: getEnvAsInt("SERVER_PORT", 8080),		Server: ServerConfig{	return &Config{	_ = godotenv.Load()	// 加载 .env 文件（如果存在）func LoadConfig() *Config {}	AllowedOrigins []stringtype CORSConfig struct {}	TimestampTolerance int // 时间戳容差（秒）	SignatureSecret  string	APIKey           stringtype APIConfig struct {}	ExpireHours int	Secret      stringtype JWTConfig struct {}	Path string	Type string // sqlitetype DatabaseConfig struct {}	Env  string	Port inttype ServerConfig struct {}	CORS     CORSConfig	API      APIConfig	JWT      JWTConfig	Database DatabaseConfig	Server   ServerConfigtype Config struct {)	"github.com/joho/godotenv"	"os"	"log"