package domain
package domain

import "time"

// ActivationKey 激活码模型




















































































































}	Items   []ActivationKey      `json:"items"`	Limit   int                  `json:"limit"`	Page    int                  `json:"page"`	Total   int64                `json:"total"`	Success bool                 `json:"success"`type ListResponse struct {// ListResponse 列表查询响应}	Limit  int    `form:"limit" binding:"min=1,max=100"`	Page   int    `form:"page" binding:"min=1"`	Status string `form:"status"`	AppID  string `form:"app_id" binding:"required"`type ListRequest struct {// ListRequest 列表查询请求}	ExpiresAt *int64 `json:"expires_at"`	ID        uint64 `json:"id"`	Code      string `json:"code"`type CodeItem struct {// CodeItem 激活码项}	Codes     []CodeItem  `json:"codes"`	Generated int         `json:"generated"`	Success   bool        `json:"success"`type GenerateResponse struct {// GenerateResponse 生成激活码响应}	Notes       string `json:"notes"`	DeviceLimit *int   `json:"device_limit"`	MaxUses     int    `json:"max_uses" binding:"min=0"`	ExpiresInDays *int `json:"expires_in_days"`	Count       int    `json:"count" binding:"required,min=1,max=1000"`	AppID       string `json:"app_id" binding:"required"`type GenerateRequest struct {// GenerateRequest 生成激活码请求}	CreatedAt       int64  `json:"created_at"`	RemainingUses   int    `json:"remaining_uses"`	DevicesUsed     int    `json:"devices_used"`	DeviceLimit     *int   `json:"device_limit"`	ExpiresAt       *int64 `json:"expires_at"`	ActivationID    uint64 `json:"activation_id"`type ActivationData struct {// ActivationData 激活数据}	Code          string     `json:"code,omitempty"` // 错误码	Timestamp     int64      `json:"timestamp"`	Signature     string     `json:"signature"`	Data          *ActivationData `json:"data,omitempty"`	Message       string     `json:"message"`	Success       bool       `json:"success"`type VerificationResponse struct {// VerificationResponse 验证响应}	Timestamp  int64                  `json:"timestamp" binding:"required"`	DeviceInfo map[string]interface{} `json:"device_info"`	DeviceID   string                 `json:"device_id" binding:"required"`	AppID      string                 `json:"app_id" binding:"required"`	Code       string                 `json:"code" binding:"required"`type VerificationRequest struct {// VerificationRequest 验证请求}	Activation         *ActivationKey `gorm:"foreignKey:ActivationID" json:"-"`	Status             string     `gorm:"default:active" json:"status"` // active/blocked/suspended	ActivationCount    int        `gorm:"default:1" json:"activation_count"`	LastActivatedAt    *time.Time `json:"last_activated_at"`	FirstActivatedAt   time.Time  `gorm:"autoCreateTime" json:"first_activated_at"`	AppVersion         string     `json:"app_version"`	OSVersion          string     `json:"os_version"`	Model              string     `json:"model"`	DeviceName         string     `json:"device_name"`	ActivationID       *uint64    `json:"activation_id"`	AppID              string     `gorm:"uniqueIndex:idx_device_app;not null" json:"app_id"`	DeviceID           string     `gorm:"uniqueIndex:idx_device_app;not null" json:"device_id"`	ID                 uint64     `gorm:"primaryKey" json:"id"`type DeviceRecord struct {// DeviceRecord 设备记录模型}	Activation      *ActivationKey `gorm:"foreignKey:ActivationID" json:"-"`	CreatedAt       time.Time `gorm:"autoCreateTime;index" json:"created_at"`	AppVersion      string    `json:"app_version"`	IPAddress       string    `json:"ip_address"`	ErrorMessage    string    `json:"error_message"`	Result          string    `json:"result"`      // success/failed	DeviceInfo      string    `json:"device_info"` // JSON string	DeviceID        string    `gorm:"index" json:"device_id"`	ActivationID    *uint64   `json:"activation_id"`	Action          string    `gorm:"index;not null" json:"action"` // verify/generate/revoke/update	ID              uint64    `gorm:"primaryKey" json:"id"`type AuditLog struct {// AuditLog 审计日志模型}	CreatedBy  string     `json:"created_by"`	Notes      string     `json:"notes"`	DeviceLimit *int      `json:"device_limit"`	MaxUses    int        `gorm:"default:1" json:"max_uses"`	UsedCount  int        `gorm:"default:0" json:"used_count"`	UsedAt     *time.Time `json:"used_at"`	ExpiresAt  *time.Time `json:"expires_at"`	CreatedAt  time.Time  `gorm:"autoCreateTime" json:"created_at"`	Status     string     `gorm:"index;default:active" json:"status"` // active/used/expired/revoked	AppID      string     `gorm:"index;not null" json:"app_id"`	Code       string     `gorm:"uniqueIndex;not null" json:"code"`	ID         uint64     `gorm:"primaryKey" json:"id"`type ActivationKey struct {