package database
package database

import (
	"fmt"









































































}	return nil	}		return err	if err := db.Migrator().CreateIndex(&domain.DeviceRecord{}, "status"); err != nil {	}		return err	if err := db.Migrator().CreateIndex(&domain.DeviceRecord{}, "app_id"); err != nil {	// device_records 索引	}		return err	if err := db.Migrator().CreateIndex(&domain.AuditLog{}, "created_at"); err != nil {	}		return err	if err := db.Migrator().CreateIndex(&domain.AuditLog{}, "device_id"); err != nil {	}		return err	if err := db.Migrator().CreateIndex(&domain.AuditLog{}, "action"); err != nil {	// audit_logs 索引	}		return err	if err := db.Migrator().CreateIndex(&domain.ActivationKey{}, "expires_at"); err != nil {	}		return err	if err := db.Migrator().CreateIndex(&domain.ActivationKey{}, "status"); err != nil {	}		return err	if err := db.Migrator().CreateIndex(&domain.ActivationKey{}, "app_id"); err != nil {	// activation_keys 索引func CreateIndexes(db *gorm.DB) error {// 初始化数据库索引（GORM AutoMigrate 会自动处理）}	)		&domain.DeviceRecord{},		&domain.AuditLog{},		&domain.ActivationKey{},	return db.AutoMigrate(	// 创建表func AutoMigrate(db *gorm.DB) error {}	return db, nil	log.Printf("✅ Database connected: %s", dbConfig.Path)	}		return nil, fmt.Errorf("failed to migrate database: %w", err)	if err := AutoMigrate(db); err != nil {	// 自动迁移	}		return nil, fmt.Errorf("unsupported database type: %s", dbConfig.Type)	} else {		}			return nil, fmt.Errorf("failed to connect to SQLite: %w", err)		if err != nil {		db, err = gorm.Open(sqlite.Open(dbConfig.Path), &gorm.Config{})	if dbConfig.Type == "sqlite" {	var err error	var db *gorm.DBfunc InitDB(dbConfig config.DatabaseConfig) (*gorm.DB, error) {)	"gorm.io/gorm"	"gorm.io/driver/sqlite"	"github.com/yingcaihuang/webtoapp-key-server/internal/domain"	"github.com/yingcaihuang/webtoapp-key-server/internal/config"	"log"