name: Auto Check

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

concurrency:
  group: android-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Download code
        uses: actions/checkout@v6

      - name: Prepare Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Prepare Android tools
        uses: android-actions/setup-android@v3
        with:
          packages: ""

      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic

      - name: Install needed tools
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-36" \
            "build-tools;36.0.0" \
            "cmake;3.22.1" \
            "ndk;28.2.13676358"

      - name: Run checks
        run: |
          ./gradlew --no-daemon --no-configuration-cache \
            -Dkotlin.compiler.execution.strategy=in-process \
            :app:compileDebugKotlin \
            :app:testDebugUnitTest
